cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', views.orderDetail.as_view(), name='order_detail'),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('', views.reserve_table, name='reserve_table'),
    path('confirmation/<int:reservation_id>/', views.reservation_confirmation, name='reservation_confirmation'),
]

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name='search_app'

urlpatterns = [
        path('', SearchResultsListView.as_view(), name='searchResult'),
]

shop/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
app_name = 'shop'

urlpatterns = [
    path('', views.prod_list, name = 'all_products'),
    path(' <uuid:type_id>/', views.prod_list, name = 'products_by_type'),
    path('<uuid:type_id>/<uuid:product_id>/', views.product_detail, name = 'product_detail'),
]

shop/models.py
from django.db import models
import uuid
from django.urls import reverse


class Type(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'type', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'type'
        verbose_name_plural = 'types'

    def get_absolute_url(self):
        return reverse('shop:products_by_type', args=[self.id])

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True
)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.type.id, self.id]
    )

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    stars = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Type, Product, ProductReview
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.
def prod_list(request, type_id=None):
    type = None
    products = Product.objects.filter(available=True)
    if type_id:
        type = get_object_or_404(Type, id=type_id)
        products = Product.objects.filter(type=type, available=True)

        paginator = Paginator(products, 6)
        try:
            page = int(request.GET.get('page', '1'))
        except: 
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage,InvalidPage):
            products = paginator.page(paginator.num_pages)

    return render(request, 'shop/type.html', {'type':type, 'prods':products})



def product_reviews(request, product_id):
    reviews = ProductReview.objects.filter(product_id=product_id).order_by('-date_added')
    return render(request, 'product_reviews.html', {'reviews': reviews})


def product_detail(request, type_id, product_id):
    product = get_object_or_404(Product, type_id=type_id, id=product_id)

    if request.method == 'POST':
        stars = request.POST.get('stars', 3)
        content = request.POST.get('content', '')

        review = ProductReview.objects.create(product=product, stars=stars, content=content)

    return render(request, 'shop/product.html', {'product':product})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %} {% endblock %}</title>
    <link rel="icon" href="static/images/logo.png" type="static/images/logo.png">
</head>
<body>
    <div class="category">
        <div class="container-fluid bg-dark navbar-fixed-top">
        
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
        {% include 'footer.html' %}
        </div>
    </div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/footer.html
<style>
    .li{text-decoration-style: solid;

    }
    i.fab.fa-instagram {
  font-size: 2em;
  color: red;
}

</style>

<div class = "footer navbar-fixed-bottom my-footer bg-dark"> 
    <iframe src="https://map.proxi.co/r/3yzpsJ6Y1Dd4ejuNVBWv" allow="geolocation; clipboard-write" width="100%" height="625px" style="border-width: 0px;" allowfullscreen></iframe> <div style="font-family: Sans-Serif; font-size:12px;color:#000000;opacity:0.5; padding-top: 5px;"> powered by <a href="https://www.proxi.co/" style="color:#000000" target="_blank">Proxi</a> </div>
    <!-- <iframe src="https://my.atlistmaps.com/map/17601722-449d-4238-afa3-d3c6277920ea?share=true" allow="geolocation" width="100%" height="200px" frameborder="0" scrolling="no" allowfullscreen></iframe> -->
    <li class="text-white">Contact Us</li>
    <a href="https://www.instagram.com/USERNAME/"  class="fab fa-instagram" target="_blank" rel="stylesheet" >Follow us on Instagram</a>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway:800">
    <p class = "text-center" style="font-weight: bold;">&copy; SIM'S Kitchen. All Rights Reserved.</p> 
</div> 
    

shop/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark text-light py-4">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div style="text-align: center;">
                <a href="{%url 'shop:all_products' %}">
                <img  class="shoplogo" width="100px" src="{% static 'images/shoplogo.png' %}" 
                alt="Fast Food Restaurant"></a>
            </div>
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Shop
                    </a>
                    
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:all_products' %}">All Products</a></li>
                            {% for cat in links %}
                                <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                            {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'cart:cart_detail' %}">Your Cart</a>
                </li> 
                {% if item_count > 0 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i 
                        class="fas fa-shopping-cart text-light">({{item_count}})</i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i 
                    class="fas fa-shopping-cart text-light">({{item_count}})</i></a>
                </li>
                {% endif %}           

            </ul>

        </div>
    </div>
    <br>
    <br>
    <div class="container" >
        <div class="my_custom_menu">
            <ul>
                {% if user.is_authenticated %}
                <li style="color: white;">
                    Welcome, <a style="color: white;"href="#" class="dropdown-toggle" data-bs-toggle="dropdown" 
                    aria-haspopup="true" aria-expanded="false">{{ user.username }} 
                    <i class="fas fa-user-circle"></i></a>
                    <div class="dropdown-menu dropdown-menu">
                        <a href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
                    </div>
                </li>
                <li>
                    <a style="color: white;" href="{% url 'logout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
                </li>
                <li>
                    <a style="color: white;" href="{% url 'reservations:reserve_table' %}">Reserve a Table <i class="fa fa-table"></i></a>
                </li>
                {% else %}
                <li>
                    <a style="color: white;" href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
                </li>
                <li>
                    <a style="color: white;" href="{% url 'login' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li>
                    <a style="color: gray;" href="{% url 'login' %}">Reserve a Table<i class="fa fa-table"></i></a>
                </li>
                {% endif %}
            </ul>   
            
        </div>
        <div>
            <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" >Search</button>
                <br>
            </form> 
        </div>
        
    </div>
    
</nav>
<hr class="text-light">