cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

shop/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
app_name = 'shop'

urlpatterns = [
    path('', views.prod_list, name = 'all_products'),
    path(' <uuid:type_id>/', views.prod_list, name = 'products_by_type'),
    path('<uuid:type_id>/<uuid:product_id>/', views.product_detail, name = 'product_detail'),
]

shop/models.py
from django.db import models
import uuid
from django.urls import reverse


class Type(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'type', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'type'
        verbose_name_plural = 'types'

    def get_absolute_url(self):
        return reverse('shop:products_by_type', args=[self.id])

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True
)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.type.id, self.id]
    )

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    stars = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Type, Product, ProductReview
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.
def prod_list(request, type_id=None):
    type = None
    products = Product.objects.filter(available=True)
    if type_id:
        type = get_object_or_404(Type, id=type_id)
        products = Product.objects.filter(type=type, available=True)

        paginator = Paginator(products, 6)
        try:
            page = int(request.GET.get('page', '1'))
        except: 
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage,InvalidPage):
            products = paginator.page(paginator.num_pages)

    return render(request, 'shop/type.html', {'type':type, 'prods':products})



def product_reviews(request, product_id):
    reviews = ProductReview.objects.filter(product_id=product_id).order_by('-date_added')
    return render(request, 'product_reviews.html', {'reviews': reviews})


def product_detail(request, type_id, product_id):
    product = get_object_or_404(Product, type_id=type_id, id=product_id)

    if request.method == 'POST':
        stars = request.POST.get('stars', 3)
        content = request.POST.get('content', '')

        review = ProductReview.objects.create(product=product, stars=stars, content=content)

    return render(request, 'shop/product.html', {'product':product})

shop/templates/shop/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {{ product.name }} - SIM'S Kitchen
{% endblock %}
{% block content %}
    <div class="row my_prod_row_class text-light">
        <div class="mx-auto">
            <p><a href="{% url 'shop:all_products' %}">Home</a> | <a href="{{product.type.get_url }}">{{product.type}}</a> |{{product.name}}</p>
        </div>
        <div class="container">
            <br>
            <div class="row">
            
                <div class="cl-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <div style="min-width: 18rem;">
                        <img src="{{product.image.url}}" alt="{{product.name}}">
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-light">
                    <div>
                        <h1 class="my_prod_title">{{product.name}}</h1>
                        <p>€{{product.price}}</p>
                        <p class="my_title">Product Description</p>

                        <hr>
                        <h2 class="subtitle">Reviews</h2>

                        <div class="reviews text-light">
                            {% for review in product.productreview_set.all %}
                                <div class="notification bg-light text-dark">
                                    <p>
                                        <strong>Date: </strong>{{ review.date_added|date:"Y-m-d" }},
                                        <strong>Stars: </strong>{{ review.stars }}
                                    </p>

                                    {{ review.content }}
                                </div>
                            {% empty %}
                                <div class="notification">
                                    No review yet...
                                </div>
                            {% endfor %}
                        </div>

                        <div class="notification col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                            {% if request.user.is_authenticated %}
                                <form  method='post' action=".">
                                    {% csrf_token %}
 
                                    <div class="field">
                                        <label>Stars</label>

                                        <div class="control">
                                            <select name="stars" id="">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3" selected>3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>

                                        <div class="field">
                                            <label>Content</label>
                                            
                                            <div class="control">
                                                <textarea class="textarea bg-secondary" name="content" id="" cols="30" rows="10"></textarea>
                                            </div>

                                        </div>

                                        <div class="field">
                                            <div class="control">
                                                <button class="button is-success">Submit</button>
                                            </div>
                                        </div>

                                    </div>
                                </form>
                            {% else %}
                                <p>Please sign-in to add review</p>
                            {% endif %}
                        </div>
                

                        <p class="text-justify my_prod_text">{{product.description}}</p>
                        {% if product.stock == 0%}
                            <p class="text-justify my_prod_text text-danger far fa-window-close"><b>  Sorry, Out of Stock</b></p>
                        {% else %}
                            <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">Add to Cart <i class="fa fa-shopping-cart"></i></a>
                            
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/type.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    {% if type %}
        {{ type.description|truncatewords:155 }}
    {% else %}
        Welcome to Sim's Kitchen - Great food at your fingertips
    {% endif %}
{% endblock %}
{% block title %}
    {% if type %}
        {{ type.name }} - Sim's Kitchen
    {% else %}
        Sim's Kitchen - Something for everyone
    {% endif %}
{% endblock %}
{% block content %}
    <!--Breadcrumb navigation-->
    {% if type %}
        <div class="row my_row_class text-light">
            <div class="mx-auto">
                <p><a href="{% url 'shop:all_products' %}">Our food Collection</a> | {{type.name}}</p>
            </div>
        </div>
    {% endif %}
    <div>
        {% if type %}
            <img class="my_image" src="{{type.image.url}}" alt="{{type.name}}">
        </div>
        <br>

        <div>
            <h1>{{type.name}}</h1>
            <p>{{type.description}}</p>
        </div>
    {% else %}

    
    <div class="container my-5 bg-dark text-light">
        <div class="row">
          
      
          
            <!-- Card -->
            <div class="row">
                <div class="col-lg-2 col-md-12 mb-4 mb-lg-0">
                  <!-- Card -->
                  <div
                       class="bg-image card shadow-1-strong min-width 20"
                       style="
                              background-image: url('static/images/burgers menu img.jpg');
                              min-width:18rem"
                       >
                    <div class="card-body text-white">
                      
                      
                      <a href="%20793fc0a8-a2b6-4501-9705-a3b5d5089e27" class="btn btn-outline-light">Crave a burger?</a>
                    </div>
                  </div>
                  <!-- Card -->
                </div>
            
                <div class="col-lg-4 mb-4 mb-lg-0">
                  <!-- Card -->
                  <div
                       class="bg-image card shadow-1-strong"
                       style="
                              background-image: url('static/images/beverages_menu.jpg');
                              "
                       >
                    <div class="card-body text-white">
                      
                      
                      <a href="%20cb15d744-c30c-41e2-870d-06ab92e3fb4f/" class="btn btn-outline-light">Feeling thirsty?</a>
                    </div>
                  </div>
                  <!-- Card -->
                </div>

                <div class="col-lg-2 col-md-12 mb-4 mb-lg-0">
                    <!-- Card -->
                    <div
                         class="bg-image card shadow-1-strong"
                         style="
                                background-image: url('static/images/burgers menu img.jpg');
                                "
                         >
                      <div class="card-body text-white">
                        
                        
                        <a href="/%201df117f8-a493-4b90-b5ee-ba745bafecf5/" class="btn btn-outline-light">Want a meal deal?</a>
                      </div>
                    </div>
                    <!-- Card -->
                  </div>
            
                <div class="col-lg-4 mb-4 mb-lg-0">
                  <!-- Card -->
                  <div
                       class="bg-image card shadow-1-strong"
                       style="
                              background-image: url('static/images/pizza menu.jpg');
                              "
                       >
                    <div class="card-body text-white">
                      
                      
                      <a href="%208b78cb03-d999-487e-875c-4e7e6408882c/" class="btn btn-outline-light">Check out our Pizzas</a>
                    </div>
                  </div>
                  <!-- Card -->
                </div>
              </div>
            <!-- Card -->
          </div>
      


    <br>
    <div class="info-container bg-dark">
        <h1 class="text-center my_title">Our menu range</h1>
        <p class="text-justify">Serving the best food at your fingertips.</p>
      <br>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx-auto">
            {% for product in prods %}
                <div class="my_bottom_margin col-9 col-lg-4 col-sm-12 col-md-4">
                    <a href="{{product.get_absolute_url}}"><img
                        class="card-img-top my_image "
                            src="{{product.image.url}}"
                                alt="{{product.name}}"></a>
                        <div class="card-body text-light">
                            <h4>{{product.name}}</h4>
                            <p>€{{product.price}}</p>
                        </div>
                </div>
            {% endfor %}
        </div>
        <br>
    </div>
{% endblock %}